services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ai
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

  ai:
    build: ./ai-python
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge
